name: Run Tests and Deploy to Render

on:
  push:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      USER_ID: ${{ secrets.USER_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      TASK_ID: ${{ secrets.TASK_ID }}
      MOCK_NAME: ${{ secrets.MOCK_NAME }}
      MOCK_EMAIL: ${{ secrets.MOCK_EMAIL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    needs: test  # Ensures deployment only happens if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST -d '{}' \
          -H "Authorization: Bearer ${{ secrets.RENDER_DEPLOY_HOOK }}" \
          "https://api.render.com/deploy/srv-cufulodsvqrc73fu3pog"